import { Injectable, OnModuleInit } from '@nestjs/common';
import { Stock } from './schemas/stock.schema';
import { Model } from 'mongoose';
import { InjectModel } from '@nestjs/mongoose';
import { StocksService } from './stocks.service';
import { mockStockData } from './tools/mockStockData';

@Injectable()
export class StocksSeedingService implements OnModuleInit {
  constructor(
    private stocksService: StocksService,
    @InjectModel(Stock.name) private stocksModel: Model<Stock>,
  ) {}

  async onModuleInit() {
    const stocks = await this.stocksModel.find().exec();
    if (stocks.length > 0) return;

    MOCK_STOCKS.forEach(stock => {
      this.stocksService.createStock(stock);
    });
  }
}

const MOCK_STOCKS = [
  {
    symbol: 'AAPL',
    name: 'Apple',
    description:
      'Apple, Inc engages in the design, manufacture, and sale of smartphones, personal computers, tablets, wearables and accessories, and other variety of related services. It operates through the following geographical segments: Americas, Europe, Greater China, Japan, and Rest of Asia Pacific. The Americas segment includes North and South America. The Europe segment consists of European countries, as well as India, the Middle East, and Africa. The Greater China segment comprises of China, Hong Kong, and Taiwan. The Rest of Asia Pacific segment includes Australia and Asian countries. Its products and services include iPhone, Mac, iPad, AirPods, Apple TV, Apple Watch, Beats products, Apple Care, iCloud, digital content stores, streaming, and licensing services. The company was founded by Steven Paul Jobs, Ronald Gerald Wayne, and Stephen G. Wozniak in 1976 and is headquartered in Cupertino, CA.',
    data: mockStockData('AAPL', 185),
  },
  {
    symbol: 'TSLA',
    name: 'Tesla',
    description:
      'Tesla, Inc engages in the design, development, manufacture, and sale of fully electric vehicles, energy generation and storage systems. It also provides vehicle service centers, supercharger station, and self-driving capability. The company operates through the following segments: Automotive and Energy Generation and Storage. The Automotive segment includes the design, development, manufacture and sale of electric vehicles. The Energy Generation and Storage segment includes the design, manufacture, installation, sale, and lease of stationary energy storage products and solar energy systems, and sale of electricity generated by its solar energy systems to customers. It develops energy storage products for use in homes, commercial facilities and utility sites. The company was founded by Jeffrey B. Straubel, Elon Reeve Musk, Martin Eberhard, and Marc Tarpenning on July 1, 2003 and is headquartered in Palo Alto, CA.',
    data: mockStockData('TSLA', 240),
  },
  {
    symbol: 'NFLX',
    name: 'Netflix, Inc.',
    description:
      'Netflix, Inc operates as a streaming entertainment service company. The firm provides subscription service streaming movies and television episodes over the Internet and sending DVDs by mail. It operates through the following segments: Domestic Streaming, International Streaming and Domestic DVD. The Domestic Streaming segment derives revenues from monthly membership fees for services consisting of streaming content to its members in the United States. The International Streaming segment includes fees from members outside the United States. The Domestic DVD segment covers revenues from services consisting of DVD-by-mail. The company was founded by Marc Randolph and Wilmot Reed Hastings Jr. on August 29, 1997 and is headquartered in Los Gatos, CA.',
    data: mockStockData('NFLX', 485),
  },
];
